spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: WARN
    com.marketcurrency: INFO
